title: Drake.fyi
markdown: kramdown
description: "drake.fyi"

baseurl: ""

license: "CC BY 4.0"

# for atom feed
author:
  name: Drakefy
  email:

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
